preprocess:
  input: data/raw/pima_diabetes_synthetic.csv
  output: data/processed/pima_diabetes_synthetic.csv

train:
  data: data/raw/pima_diabetes_synthetic.csv
  model: models/logistic_regression_model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5
